# Generated by Django 5.2 on 2025-05-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('departure', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
