# Generated by Django 5.2 on 2025-05-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tourpackage_upcoming_date_alter_tourpackage_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='upcoming_date',
            field=models.DateField(null=True),
        ),
    ]
